### ISSUE TITLE
Is rabbitmq / cbconsumer used?

### ISSUE THREAD

**Issue by strazzere** [carbonblack/cb-integration#23]
Pardon, is `cbconsumer` (backed by rabbitmq) actually used?
https://github.com/carbonblack/cb-integration/blob/0dfdb4ed42115ccc1d82be2bc7114db86e2a9855/cbint/detonation.py#L79-L103

It is instanciated here, however I can't see any documentation on configuring it. It seems to always fail since `amqp_url` is not defined in the default config. However, this could be added... Though the docker files do not install rabbitmq and no code seems to viably use this.

Can this be killed since it appears to actually be using celery workers?

**Comment by askthedragon** [comment]
Yes,  the idea here is to have this consume listen for new binaries coming into Cb Response and add them into the queue
